### ISSUE TITLE
Update index.html meta description 

### ISSUE THREAD

**Issue by steph-meyering** [steph-meyering/co-habit#45]
![image](https://user-images.githubusercontent.com/51059396/77378754-2da90500-6d34-11ea-9116-e8edbe46c7fc.png)

**Comment by sara-ls** [comment]
- [ ] Update description meta tag
- [ ] Add author + keywords meta tags 
- [ ] Update favicon

```
<meta name="author" content="Steven Davies">
<meta name="author" content="Sara Sampson">
<meta name="author" content="Stephane Meyering">
<meta name="keywords" content="___________________________">
```
